Repository BuildForSDG/Team-270-PulaniFront, pull requests merged in 2020-05, with the labels that each got.

#4 Add a Codacy badge to README.md
  README.md
Labels: enhancement

#5 Upgrade to use `react-admin`
  .eslintrc.js
  .huskyrc
  .lintstagedrc
  .stylelintrc
  __tests__/app.test.js
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/app.js
  src/index.css
  src/index.html
  src/index.js
  src/serviceWorker.js
  yarn.lock
Labels: enhancement, good first issue

#9 P 003/update readme
  README.md
  package-lock.json
  package.json
Labels: documentation
